/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package coffeshop;

import java.text.DecimalFormat;

/**
 *
 * @author Mohammed
 */
public class NewJFrame extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
    public NewJFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        radcaffe = new javax.swing.JRadioButton();
        radCap = new javax.swing.JRadioButton();
        radAm = new javax.swing.JRadioButton();
        radDop = new javax.swing.JRadioButton();
        chkBag = new javax.swing.JCheckBox();
        radAff = new javax.swing.JRadioButton();
        chkAppPie = new javax.swing.JCheckBox();
        jScrollPane7 = new javax.swing.JScrollPane();
        subText = new javax.swing.JTextPane();
        jScrollPane8 = new javax.swing.JScrollPane();
        textTaxt = new javax.swing.JTextPane();
        testTotal = new javax.swing.JScrollPane();
        TextTotal = new javax.swing.JTextPane();
        jLabel11 = new javax.swing.JLabel();
        radMatcha = new javax.swing.JRadioButton();
        radTea = new javax.swing.JRadioButton();
        chkChryPie = new javax.swing.JCheckBox();
        chkMering = new javax.swing.JCheckBox();
        chkMar = new javax.swing.JCheckBox();
        radLoose = new javax.swing.JRadioButton();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        chkCake = new javax.swing.JCheckBox();
        chkCr = new javax.swing.JCheckBox();
        chkTos = new javax.swing.JCheckBox();
        jLabel7 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        btnExit = new javax.swing.JButton();
        btnEnt = new javax.swing.JButton();
        btnCler = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/coffeshop/Photo.png"))); // NOI18N
        jLabel8.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jLabel8.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);
        jPanel3.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 100, 410, 530));

        jLabel10.setBackground(new java.awt.Color(93, 44, 2));
        jLabel10.setFont(new java.awt.Font("Chaparral Pro", 2, 48)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(93, 44, 2));
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("Coffe Shop");
        jLabel10.setAutoscrolls(true);
        jLabel10.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel3.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 10, 230, 60));

        radcaffe.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        radcaffe.setText("Espresso");
        radcaffe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radcaffeActionPerformed(evt);
            }
        });
        jPanel3.add(radcaffe, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 150, -1, -1));

        radCap.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        radCap.setText("Cappuccino");
        radCap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radCapActionPerformed(evt);
            }
        });
        jPanel3.add(radCap, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 180, -1, -1));

        radAm.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        radAm.setText("Americano");
        radAm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radAmActionPerformed(evt);
            }
        });
        jPanel3.add(radAm, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 210, -1, -1));

        radDop.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        radDop.setText("Doppio ");
        radDop.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radDopActionPerformed(evt);
            }
        });
        jPanel3.add(radDop, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 240, -1, -1));

        chkBag.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        chkBag.setText("Bagles");
        jPanel3.add(chkBag, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 240, -1, -1));

        radAff.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        radAff.setText("Affogato");
        radAff.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radAffActionPerformed(evt);
            }
        });
        jPanel3.add(radAff, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 270, -1, -1));

        chkAppPie.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        chkAppPie.setText("Apple Pie");
        jPanel3.add(chkAppPie, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 270, -1, -1));

        jScrollPane7.setViewportView(subText);

        jPanel3.add(jScrollPane7, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 420, 150, -1));

        jScrollPane8.setViewportView(textTaxt);

        jPanel3.add(jScrollPane8, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 460, 150, -1));

        testTotal.setViewportView(TextTotal);

        jPanel3.add(testTotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 500, 150, -1));

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel11.setText("Tax");
        jPanel3.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 460, 30, -1));

        radMatcha.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        radMatcha.setText("Matcha");
        radMatcha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radMatchaActionPerformed(evt);
            }
        });
        jPanel3.add(radMatcha, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 300, -1, -1));

        radTea.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        radTea.setText("Tea Latte");
        radTea.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radTeaActionPerformed(evt);
            }
        });
        jPanel3.add(radTea, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 360, -1, -1));

        chkChryPie.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        chkChryPie.setText("Cherry Pie");
        jPanel3.add(chkChryPie, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 300, -1, -1));

        chkMering.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        chkMering.setText("Meringue");
        jPanel3.add(chkMering, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 360, -1, -1));

        chkMar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        chkMar.setText("Macroons");
        jPanel3.add(chkMar, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 330, -1, -1));

        radLoose.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        radLoose.setText("Loose Leaf Green");
        radLoose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radLooseActionPerformed(evt);
            }
        });
        jPanel3.add(radLoose, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 330, -1, -1));

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel12.setText("Subtotal");
        jPanel3.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 420, 60, 20));

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel13.setText("Total");
        jPanel3.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 500, 50, -1));

        jLabel14.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(46, 34, 5));
        jLabel14.setText("Desserts");
        jPanel3.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 110, -1, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(46, 34, 5));
        jLabel4.setText("Drinks");
        jPanel3.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 110, -1, -1));

        chkCake.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        chkCake.setText("Chocolate Cake");
        jPanel3.add(chkCake, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 150, -1, -1));

        chkCr.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        chkCr.setText("Croissant");
        chkCr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkCrActionPerformed(evt);
            }
        });
        jPanel3.add(chkCr, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 180, -1, -1));

        chkTos.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        chkTos.setText("Toast");
        jPanel3.add(chkTos, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 210, -1, -1));

        jLabel7.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(51, 51, 51));
        jLabel7.setText(" $3.25");
        jPanel3.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 360, 50, 20));

        jLabel9.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(51, 51, 51));
        jLabel9.setText(" $1.95");
        jPanel3.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 150, 50, 20));

        jLabel15.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(51, 51, 51));
        jLabel15.setText(" $3.25");
        jPanel3.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 180, 50, 20));

        jLabel16.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(51, 51, 51));
        jLabel16.setText(" $2.15");
        jPanel3.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 210, 50, 20));

        jLabel17.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(51, 51, 51));
        jLabel17.setText(" $2.50");
        jPanel3.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 240, 50, 20));

        jLabel18.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(51, 51, 51));
        jLabel18.setText(" $3.75");
        jPanel3.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 270, 50, 20));

        jLabel19.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(51, 51, 51));
        jLabel19.setText(" $2.15");
        jPanel3.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 300, 50, 20));

        jLabel20.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(51, 51, 51));
        jLabel20.setText(" $3.00");
        jPanel3.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 330, 50, 20));

        jLabel21.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(51, 51, 51));
        jLabel21.setText(" $4.00");
        jPanel3.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 150, 50, 20));

        jLabel22.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(51, 51, 51));
        jLabel22.setText(" $1.25");
        jPanel3.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 180, 50, 20));

        jLabel23.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(51, 51, 51));
        jLabel23.setText(" $0.75");
        jPanel3.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 210, 50, 20));

        jLabel24.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(51, 51, 51));
        jLabel24.setText(" $1.25");
        jPanel3.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 240, 50, 20));

        jLabel25.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(51, 51, 51));
        jLabel25.setText(" $3.75");
        jPanel3.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 270, 50, 20));

        jLabel26.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        jLabel26.setForeground(new java.awt.Color(51, 51, 51));
        jLabel26.setText(" $3.50");
        jPanel3.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 300, 50, 20));

        jLabel27.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        jLabel27.setForeground(new java.awt.Color(51, 51, 51));
        jLabel27.setText(" $2.00");
        jPanel3.add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 330, 50, 20));

        jLabel28.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        jLabel28.setForeground(new java.awt.Color(51, 51, 51));
        jLabel28.setText(" $7.00");
        jPanel3.add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 360, 50, 20));

        btnExit.setBackground(new java.awt.Color(93, 44, 2));
        btnExit.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnExit.setForeground(new java.awt.Color(255, 255, 255));
        btnExit.setText("Exit");
        btnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExitActionPerformed(evt);
            }
        });
        jPanel3.add(btnExit, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 570, 90, 30));

        btnEnt.setBackground(new java.awt.Color(93, 44, 2));
        btnEnt.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnEnt.setForeground(new java.awt.Color(255, 255, 255));
        btnEnt.setText("Enter");
        btnEnt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEntActionPerformed(evt);
            }
        });
        jPanel3.add(btnEnt, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 570, 90, 30));

        btnCler.setBackground(new java.awt.Color(93, 44, 2));
        btnCler.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnCler.setForeground(new java.awt.Color(255, 255, 255));
        btnCler.setText("Clear");
        btnCler.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClerActionPerformed(evt);
            }
        });
        jPanel3.add(btnCler, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 570, 90, 30));

        jPanel2.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 850, 630));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 845, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 636, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void chkCrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkCrActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_chkCrActionPerformed

    private void radcaffeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radcaffeActionPerformed
        // selected expriso
         if(radcaffe.isSelected()){
            
            radCap.setSelected(false);
            radAm.setSelected(false);
            radDop.setSelected(false);
            radAff.setSelected(false);
            radMatcha.setSelected(false);
            radLoose.setSelected(false);
            radTea.setSelected(false);
        
        }
        
        
        
        
        
    }//GEN-LAST:event_radcaffeActionPerformed

    private void radCapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radCapActionPerformed
        // selected cap
        
            if(radCap.isSelected()){
            
            radcaffe.setSelected(false);
            radAm.setSelected(false);
            radDop.setSelected(false);
            radAff.setSelected(false);
            radMatcha.setSelected(false);
            radLoose.setSelected(false);
            radTea.setSelected(false);
        
        }
    }//GEN-LAST:event_radCapActionPerformed

    private void radAmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radAmActionPerformed
        // Selected Cafee Amircano
            if(radAm.isSelected()){
            
            radCap.setSelected(false);
            radcaffe.setSelected(false);
            radDop.setSelected(false);
            radAff.setSelected(false);
            radMatcha.setSelected(false);
            radLoose.setSelected(false);
            radTea.setSelected(false);
        
        }
        
    }//GEN-LAST:event_radAmActionPerformed

    private void radDopActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radDopActionPerformed
        //Selected Doppio
            if(radDop.isSelected()){
            
            radCap.setSelected(false);
            radAm.setSelected(false);
            radcaffe.setSelected(false);
            radAff.setSelected(false);
            radMatcha.setSelected(false);
            radLoose.setSelected(false);
            radTea.setSelected(false);
        
        }
    }//GEN-LAST:event_radDopActionPerformed

    private void radAffActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radAffActionPerformed
        // Selected Affogato
            if(radAff.isSelected()){
            
            radCap.setSelected(false);
            radAm.setSelected(false);
            radDop.setSelected(false);
            radcaffe.setSelected(false);
            radMatcha.setSelected(false);
            radLoose.setSelected(false);
            radTea.setSelected(false);
        
        }
    }//GEN-LAST:event_radAffActionPerformed

    private void radMatchaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radMatchaActionPerformed
        // Selected Matcha 
            if(radMatcha.isSelected()){
            
            radCap.setSelected(false);
            radAm.setSelected(false);
            radDop.setSelected(false);
            radAff.setSelected(false);
            radcaffe.setSelected(false);
            radLoose.setSelected(false);
            radTea.setSelected(false);
        
        }
    }//GEN-LAST:event_radMatchaActionPerformed

    private void radLooseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radLooseActionPerformed
        // Selcted Loose Leaf Green
           if(radLoose.isSelected()){
            
            radCap.setSelected(false);
            radAm.setSelected(false);
            radDop.setSelected(false);
            radAff.setSelected(false);
            radcaffe.setSelected(false);
            radMatcha.setSelected(false);
            radTea.setSelected(false);
        
        }
        
    }//GEN-LAST:event_radLooseActionPerformed

    private void radTeaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radTeaActionPerformed
        // Selected Tea Latte
              if(radTea.isSelected()){
            
            radCap.setSelected(false);
            radAm.setSelected(false);
            radDop.setSelected(false);
            radAff.setSelected(false);
            radcaffe.setSelected(false);
            radMatcha.setSelected(false);
            radLoose.setSelected(false);
        
        }
        
        
    }//GEN-LAST:event_radTeaActionPerformed

    private void btnEntActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEntActionPerformed
        // TODO add your handling code here:
        
        DecimalFormat df = new DecimalFormat("$0.00");
        double subtotal = 0;
        double total;
        final double TAXRATE = .08;
        double tax;
        
        // for radio button
        if(radcaffe.isSelected()){
              subtotal = subtotal + 1.95;
        }else if(radCap.isSelected()){
              subtotal = subtotal + 3.25;
        }else if(radAm.isSelected()){
              subtotal = subtotal + 2.15;
        }else if(radDop.isSelected()){
              subtotal = subtotal + 2.50;
        }else if(radAff.isSelected()){
              subtotal = subtotal + 3.75;
        }else if(radMatcha.isSelected()){
              subtotal = subtotal + 2.15;
        }else if(radLoose.isSelected()){
              subtotal = subtotal + 3;
        }else if(radTea.isSelected()){
              subtotal = subtotal + 3.25;
        } 
        
        
        // for chek box
        if(chkCake.isSelected()){
            subtotal = subtotal + 4;
        } if(chkCr.isSelected()){
            subtotal = subtotal + 1.25;
        } if(chkTos.isSelected()){
            subtotal = subtotal + .75;
        } if(chkBag.isSelected()){
            subtotal = subtotal + 1.25;
        } if(chkAppPie.isSelected()){
            subtotal = subtotal + 3.75;
        } if(chkChryPie.isSelected()){
            subtotal = subtotal + 3.50;
        } if(chkMar.isSelected()){
            subtotal = subtotal + 2;
        } if(chkMering.isSelected()){
            subtotal = subtotal + 7;
        }
        
        
        
        subText.setText(Double.toString(subtotal ));
             
        subtotal = Double.parseDouble(subText.getText());
        tax = subtotal * TAXRATE;
        total = subtotal + tax;
        
        textTaxt.setText(Double.toString(tax));
        TextTotal.setText(Double.toString(total));
        
        
        // only decimal Number
        subText.setText(df.format(subtotal));
        textTaxt.setText(df.format(tax));
        TextTotal.setText(df.format(total));
        
        
        
        
        
        
        
        
        
        
        
    }//GEN-LAST:event_btnEntActionPerformed

    private void btnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExitActionPerformed
        // exit jFrame
        
        System.exit(0);
        
    }//GEN-LAST:event_btnExitActionPerformed

    private void btnClerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClerActionPerformed
        // Cler all fields
            radcaffe.setSelected(false);
            radCap.setSelected(false);
            radAm.setSelected(false);
            radDop.setSelected(false);
            radAff.setSelected(false);
            radMatcha.setSelected(false);
            radLoose.setSelected(false);
            radTea.setSelected(false);
            
            chkCake.setSelected(false);
            chkCr.setSelected(false);
            chkTos.setSelected(false);
            chkBag.setSelected(false);
            chkAppPie.setSelected(false);
            chkChryPie.setSelected(false);
            chkMar.setSelected(false);
            chkMering.setSelected(false);
            subText.setText("");
            textTaxt.setText("");
            TextTotal.setText("");
            
        
        
        
        
    }//GEN-LAST:event_btnClerActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextPane TextTotal;
    private javax.swing.JButton btnCler;
    private javax.swing.JButton btnEnt;
    private javax.swing.JButton btnExit;
    private javax.swing.JCheckBox chkAppPie;
    private javax.swing.JCheckBox chkBag;
    private javax.swing.JCheckBox chkCake;
    private javax.swing.JCheckBox chkChryPie;
    private javax.swing.JCheckBox chkCr;
    private javax.swing.JCheckBox chkMar;
    private javax.swing.JCheckBox chkMering;
    private javax.swing.JCheckBox chkTos;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JScrollPane jScrollPane8;
    private javax.swing.JRadioButton radAff;
    private javax.swing.JRadioButton radAm;
    private javax.swing.JRadioButton radCap;
    private javax.swing.JRadioButton radDop;
    private javax.swing.JRadioButton radLoose;
    private javax.swing.JRadioButton radMatcha;
    private javax.swing.JRadioButton radTea;
    private javax.swing.JRadioButton radcaffe;
    private javax.swing.JTextPane subText;
    private javax.swing.JScrollPane testTotal;
    private javax.swing.JTextPane textTaxt;
    // End of variables declaration//GEN-END:variables
}
